server {
    listen 8080;

    include /etc/nginx/mime.types;

    types {
        application/javascript mjs;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}