name: CI Pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Socket Firewall Free
              uses: socketdev/action@v1
              with:
                  mode: firewall-free

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13.5"

            - name: Install Backend Dependencies
              working-directory: ./backend
              run: sfw pip install -r requirements.txt

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Install Frontend Dependencies
              working-directory: ./frontend
              run: deno install

            - name: Audit Frontend dependencies
              working-directory: ./frontend
              run: deno audit --socket

            - name: Build Frontend
              working-directory: ./frontend
              run: deno task build
